In [1]:
a=[[1,2],[3,4]]
np.mean(a,axis=1)


NameError: name 'np' is not defined

In [2]:
import numpy as np
a=[[1,2],
   [3,4]]
np.mean(a,axis=1)

array([1.5, 3.5])

In [3]:
np.max(a)

4

In [5]:
np.where(max(a))

(array([0, 1], dtype=int64),)

In [6]:
np.where(max(a))

(array([0, 1], dtype=int64),)

In [7]:
np.where[max(a)]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [8]:
np.where(max(a),axis=1)

TypeError: where() takes no keyword arguments

In [9]:
np.max(a)


4

In [10]:
i,j=np.where(a==np.max(a))
i,j

(array([1], dtype=int64), array([1], dtype=int64))

array([5, 2, 4])

array([7, 7, 9])

array([8, 6, 9])

In [53]:
a=np.arange(6)

In [75]:
import numpy as np
a=np.array([[10,20,30,40,50,60,70,80,90]]).reshape(3,3)
print (a) 
print ('\n')
print (a[...,2])
print ('\n')
print (a[1,...])
print ('\n')
y= a[0:2,[0,1]]
print (y)


[[10 20 30]
 [40 50 60]
 [70 80 90]]


[30 60 90]


[40 50 60]


[[10 20]
 [40 50]]
